startproject:
	django-admin startproject first_project

run-server:
	python manage.py runserver

startapp:
	python manage.py startapp products


migrate:
	python manage.py migrate

make-migrations:
	python manage.py makemigrations products

createsuperuser:
	python manage.py createsuperuser