startproject:
	django-admin startproject first_project

run-server:
	python manage.py runserver

startapp:
	python manage.py startapp news


migrate:
	python manage.py migrate

make-migrations:
	python manage.py makemigrations news

createsuperuser:
	python manage.py createsuperuser